"""add reviews

Revision ID: 26ce70d2cec9
Revises: 82ed29844bb1
Create Date: 2026-09-16 21:29:11.206260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '26ce70d2cec9'
down_revision: Union[str, None] = '82ed29844bb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('student_id', app.database.types.GUID(), nullable=False),
    sa.Column('course_id', app.database.types.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_review_student_course')
    )
    op.create_index(op.f('ix_reviews_course_id'), 'reviews', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_course_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
