"""add enrollments wishlists notifications

Revision ID: 3d4ce3309503
Revises: 3ebbd07a4a86
Create Date: 2026-09-16 11:28:33.550202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '3d4ce3309503'
down_revision: Union[str, None] = '3ebbd07a4a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('user_id', app.database.types.GUID(), nullable=False),
    sa.Column('type', sa.Enum('course_approved', 'course_rejected', 'new_enrollment', 'certificate_available', 'general', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_id', app.database.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('student_id', app.database.types.GUID(), nullable=False),
    sa.Column('course_id', app.database.types.GUID(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    op.create_table('wishlists',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('student_id', app.database.types.GUID(), nullable=False),
    sa.Column('course_id', app.database.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_wishlist_student_course')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlists')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
