"""add payments

Revision ID: 6ce169839bc1
Revises: 26ce70d2cec9
Create Date: 2026-09-17 12:39:10.626764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '6ce169839bc1'
down_revision: Union[str, None] = '26ce70d2cec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('student_id', app.database.types.GUID(), nullable=False),
    sa.Column('course_id', app.database.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='payment_status'), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_course_id'), 'payments', ['course_id'], unique=False)
    op.create_index(op.f('ix_payments_student_id'), 'payments', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_student_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_course_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
