"""add certificate settings table

Revision ID: 945a97a2253a
Revises: bb94aa1b8f00
Create Date: 2026-09-19 20:59:51.580766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '945a97a2253a'
down_revision: Union[str, None] = 'bb94aa1b8f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_settings',
    sa.Column('id', app.database.types.GUID(), nullable=False),
    sa.Column('background_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificate_settings')
    # ### end Alembic commands ###
